name: PostHog Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init posthog

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: gmichelo/posthog-benchmark:latest

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init posthog

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
          push: true
          tags: gmichelo/posthog-benchmark:latest

  notify-failures:
    name: Notify on build failures
    needs:
      - docker-build
      - nsc-build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: failure() && needs.docker-build.result == 'success' && needs.nsc-build.result == 'failure'
    steps:
      - uses: ruby/action-slack@v3.2.1
        with:
          payload: |
            {
              "attachments": [{
                "title": "Namespace build failed while Docker build passed! Check now: ${{ job.status }}: ${{ github.workflow }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "See the link",
                "fields": [],
                "footer": "",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
