name: PostHog Push DockerHub Benchmark
on:
  push:
  workflow_dispatch:
    inputs:
      posthog-commit-id:
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init posthog

      - if: ${{ github.event.inputs.posthog-commit-id }} != ""
        run: cd posthog && git checkout ${{ github.event.inputs.posthog-commit-id }}

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: gmichelo/posthog-benchmark:latest-gh-runner

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init posthog

      - if: ${{ github.event.inputs.posthog-commit-id }} != ""
        run: cd posthog && git checkout ${{ github.event.inputs.posthog-commit-id }}

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
          push: true
          tags: gmichelo/posthog-benchmark:latest-nsc-build
  
  nsc-runner-build:
    name: Build in Namespace
    runs-on: namespace-profile-push-benchmark
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init posthog

      - if: ${{ github.event.inputs.posthog-commit-id }} != ""
        run: cd posthog && git checkout ${{ github.event.inputs.posthog-commit-id }}

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: gmichelo/posthog-benchmark:latest-nsc-runner

